version: '3.9'

services:
  mssql:
    image: liaisonintl/mssql-server-linux
    container_name: mssqlserver
    ports:
      - 1433:1433
    volumes:
      - ./SQL:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Tuan2903
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8
      - TZ=America/New_York
  blazorappec.server:
    image: ${DOCKER_REGISTRY-}blazorappec
    build:
      context: .
      dockerfile: BlazorAppEC/Server/Dockerfile